/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { FileDto } from '../models/file-dto';
export interface BusinessInfoResponseDto {

  /**
   * 주소
   */
  address: string;

  /**
   * 사업자 등록번호
   */
  businessNumber: string;

  /**
   * 대표자명
   */
  ceoName: string;

  /**
   * 회사명
   */
  companyName: string;

  /**
   * 연락처
   */
  contactNumber: string;

  /**
   * 생성일
   */
  createdAt: string;

  /**
   * 삭제일
   */
  deletedAt?: string;

  /**
   * 이메일
   */
  email: string;

  /**
   * 사업 정보 ID
   */
  id: string;

  /**
   * 연결된 이미지 파일
   */
  image?: FileDto;

  /**
   * 수정일
   */
  updatedAt: string;
}
