/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CreatePortfolioDto {

  /**
   * 설명
   */
  description: string;
  imageIds?: Array<string>;

  /**
   * 이미지 URL
   */
  imageUrls?: Array<string>;

  /**
   * 제목
   */
  title: string;
}
