/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CreateProductDto {

  /**
   * 제품 설명
   */
  description: string;

  /**
   * 연결할 이미지 File ID
   */
  imageId?: string | null;

  /**
   * 노출 여부
   */
  isExposed: boolean;

  /**
   * 상품 링크 URL
   */
  link?: string | null;

  /**
   * 가격
   */
  price?: number | null;

  /**
   * 제품 타입
   */
  productType: 'GPU_SERVER' | 'MOBILE_APP' | 'WEB_APP_MAINT' | 'CLOUD_INFRA' | 'TECH_CONSULT';
}
