/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CreateInquiryDto {

  /**
   * 연락 가능 시간대
   */
  availableTime?: string;

  /**
   * 회사명
   */
  companyName?: string;

  /**
   * 연락처
   */
  contact: string;

  /**
   * 문의 내용
   */
  content: string;

  /**
   * 이메일
   */
  email: string;

  /**
   * 연결할 이미지 File ID 배열
   */
  images?: Array<string> | null;

  /**
   * 작성자 이름
   */
  name: string;

  /**
   * 제품 유형
   */
  productType?: 'GPU_SERVER' | 'MOBILE_APP' | 'WEB_APP_MAINT' | 'CLOUD_INFRA' | 'TECH_CONSULT';

  /**
   * 문의 유형
   */
  type?: 'PRODUCT' | 'APP' | 'ETC';
}
