/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface FileDto {

  /**
   * 파일 ID
   */
  id: string;

  /**
   * 파일명
   */
  name: string;

  /**
   * 파일 크기
   */
  size: number;

  /**
   * URL
   */
  url: string;
}
