/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { FileDto } from '../models/file-dto';
export interface InquiryResponseDto {

  /**
   * 연락 가능 시간대
   */
  availableTime?: string;

  /**
   * 회사명
   */
  companyName?: string;

  /**
   * 연락처
   */
  contact: string;

  /**
   * 문의 내용
   */
  content: string;

  /**
   * 생성일
   */
  createdAt: string;

  /**
   * 삭제일
   */
  deletedAt?: string;

  /**
   * 이메일
   */
  email: string;

  /**
   * 문의 ID
   */
  id: string;

  /**
   * 연결된 이미지 파일 목록
   */
  images?: Array<FileDto>;

  /**
   * 처리 대기 여부
   */
  isPending: boolean;

  /**
   * 작성자 이름
   */
  name: string;

  /**
   * 제품 유형
   */
  productType?: 'GPU_SERVER' | 'MOBILE_APP' | 'WEB_APP_MAINT' | 'CLOUD_INFRA' | 'TECH_CONSULT';

  /**
   * 문의 유형
   */
  type?: 'PRODUCT' | 'APP' | 'ETC';

  /**
   * 수정일
   */
  updatedAt: string;
}
