/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { JobNoitceDto } from '../models/job-noitce-dto';
export interface JobNoticeResponseDto {
  items: Array<JobNoitceDto>;
  totalCount: number;
}
