/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface JobNoitceDto {
  admin: string;
  content?: string;
  createdAt?: string;
  id?: string;

  /**
   * 첨부 이미지 경로들
   */
  images: Array<string>;
  isPinned?: boolean;

  /**
   * 화면에 표시할 게시물 번호
   */
  rowNumber: number;
  seq?: number;
  title?: string;
  views?: number;
}
