/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { FileDto } from '../models/file-dto';
export interface PortfolioResponseDto {

  /**
   * 생성일시
   */
  createdAt: string;

  /**
   * 삭제일시
   */
  deletedAt?: string;

  /**
   * 포트폴리오 설명
   */
  description: string | null;

  /**
   * 포트폴리오 ID
   */
  id: string;

  /**
   * 연결된 이미지 정보
   */
  images?: FileDto;

  /**
   * 정렬 순서
   */
  order: number;

  /**
   * 포트폴리오 제목
   */
  title: string;

  /**
   * 수정일시
   */
  updatedAt: string;

  /**
   * 포트폴리오 조회수
   */
  views: number;
}
