/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { FileDto } from '../models/file-dto';
export interface ProductResponseDto {

  /**
   * 생성일시
   */
  createdAt: string;

  /**
   * 삭제일시
   */
  deletedAt?: string;

  /**
   * 제품 설명
   */
  description: string;

  /**
   * 제품 ID
   */
  id: string;

  /**
   * 연결된 이미지 정보
   */
  image?: FileDto;

  /**
   * 이미지 File ID
   */
  imageId: string | null;

  /**
   * 노출 여부
   */
  isExposed: boolean;

  /**
   * 상품 링크 URL
   */
  link: string | null;

  /**
   * 정렬 순서
   */
  order: number;

  /**
   * 가격
   */
  price: number | null;

  /**
   * 제품 타입
   */
  productType: 'GPU_SERVER' | 'MOBILE_APP' | 'WEB_APP_MAINT' | 'CLOUD_INFRA' | 'TECH_CONSULT';

  /**
   * 수정일시
   */
  updatedAt: string;
}
