/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface UpdateBusinessInfoDto {

  /**
   * 주소
   */
  address?: string;

  /**
   * 사업자 등록번호
   */
  businessNumber?: string;

  /**
   * 대표자명
   */
  ceoName?: string;

  /**
   * 회사명
   */
  companyName?: string;

  /**
   * 연락처
   */
  contactNumber?: string;

  /**
   * 이메일
   */
  email?: string;

  /**
   * 연결할 이미지 File ID
   */
  imageId?: string | null;
}
