/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { s3ControllerUploadFiles } from '../fn/s-3/s-3-controller-upload-files';
import { S3ControllerUploadFiles$Params } from '../fn/s-3/s-3-controller-upload-files';

@Injectable({ providedIn: 'root' })
export class S3Service extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `s3ControllerUploadFiles()` */
  static readonly S3ControllerUploadFilesPath = '/s3/upload';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `s3ControllerUploadFiles()` instead.
   *
   * This method doesn't expect any request body.
   */
  s3ControllerUploadFiles$Response(params?: S3ControllerUploadFiles$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return s3ControllerUploadFiles(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `s3ControllerUploadFiles$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  s3ControllerUploadFiles(params?: S3ControllerUploadFiles$Params, context?: HttpContext): Observable<void> {
    return this.s3ControllerUploadFiles$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

}
