FROM node:22-alpine

WORKDIR /app

ARG environment

COPY package.json package-lock.json* ./
RUN npm install --force

COPY prisma /app/prisma

COPY apps/server/.env.${environment} /app/.env

RUN npx prisma generate --schema prisma

COPY dist/apps/server /app

CMD ["node", "main.js"]

EXPOSE 3000
