/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { JobNoitceDto } from '../../models/job-noitce-dto';

export interface RecruitControllerFindOne$Params {
  id: string;
}

export function recruitControllerFindOne(http: HttpClient, rootUrl: string, params: RecruitControllerFindOne$Params, context?: HttpContext): Observable<StrictHttpResponse<JobNoitceDto>> {
  const rb = new RequestBuilder(rootUrl, recruitControllerFindOne.PATH, 'get');
  if (params) {
    rb.path('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<JobNoitceDto>;
    })
  );
}

recruitControllerFindOne.PATH = '/recruit/{id}';
