/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { JobNoticeResponseDto } from '../../models/job-notice-response-dto';

export interface RecruitControllerGetNotices$Params {
  pageNo: number;
  pageSize: number;

/**
 * 검색 기능
 */
  keyword?: string;
}

export function recruitControllerGetNotices(http: HttpClient, rootUrl: string, params: RecruitControllerGetNotices$Params, context?: HttpContext): Observable<StrictHttpResponse<JobNoticeResponseDto>> {
  const rb = new RequestBuilder(rootUrl, recruitControllerGetNotices.PATH, 'get');
  if (params) {
    rb.query('pageNo', params.pageNo, {});
    rb.query('pageSize', params.pageSize, {});
    rb.query('keyword', params.keyword, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<JobNoticeResponseDto>;
    })
  );
}

recruitControllerGetNotices.PATH = '/recruit';
