/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { NgModule, ModuleWithProviders, SkipSelf, Optional } from '@angular/core';
import { HttpClient } from '@angular/common/http';
import { ApiConfiguration, ApiConfigurationParams } from './api-configuration';

import { AppService } from './services/app.service';
import { AdminService } from './services/admin.service';
import { InquiriesService } from './services/inquiries.service';
import { BusinessInfoService } from './services/business-info.service';
import { S3Service } from './services/s-3.service';
import { ProductsService } from './services/products.service';
import { PartnerService } from './services/partner.service';
import { AuthService } from './services/auth.service';
import { PortfoliosService } from './services/portfolios.service';
import { RecruitService } from './services/recruit.service';
import { StorageService } from './services/storage.service';

/**
 * Module that provides all services and configuration.
 */
@NgModule({
  imports: [],
  exports: [],
  declarations: [],
  providers: [
    AppService,
    AdminService,
    InquiriesService,
    BusinessInfoService,
    S3Service,
    ProductsService,
    PartnerService,
    AuthService,
    PortfoliosService,
    RecruitService,
    StorageService,
    ApiConfiguration
  ],
})
export class ApiModule {
  static forRoot(params: ApiConfigurationParams): ModuleWithProviders<ApiModule> {
    return {
      ngModule: ApiModule,
      providers: [
        {
          provide: ApiConfiguration,
          useValue: params
        }
      ]
    }
  }

  constructor( 
    @Optional() @SkipSelf() parentModule: ApiModule,
    @Optional() http: HttpClient
  ) {
    if (parentModule) {
      throw new Error('ApiModule is already loaded. Import in your base AppModule only.');
    }
    if (!http) {
      throw new Error('You need to import the HttpClientModule in your AppModule! \n' +
      'See also https://github.com/angular/angular/issues/20575');
    }
  }
}
